OTD-8 configuração inicial para obrigatoridade ce campo Código do set…
ccem-dev/otus-database pull request #12
Opened 2021-01-13 21:32 UTC by RI50N

…or censitário e tentativas de contato para endereços

2021-01-15 19:41 UTC, erickpoleto requested changes

2021-01-15 19:41 UTC, erickpoleto commented on database/initdb/otus-data.js
> +    {
falta campo:
{
    "value" : "ARROLADO",
    "statusColor" : "#8bdee0"
}

2021-01-15 19:42 UTC, erickpoleto approved these changes

2021-01-19 14:15 UTC, drferreira approved these changes

2021-01-19 14:16 UTC, merged